### ISSUE TITLE
Cannot open "data/COVID19LSOA.shp"; The file doesn't seem to exist.

### ISSUE THREAD

**Issue by andysouth** [VictimOfMaths/COVIDmapper#2]
Seems like the data folder and shapefile are missing from the repo :-)

**Comment by VictimOfMaths** [comment]
The shapefile is infuriatingly too large to upload here (seems weird that Shiny will accept it but GitHub won't).

I've put in the code to generate it, but I couldn't get {rmapshaper} to work, so I had to use the mapshaper.org website, so there's an external step in the code. 

All of which is rather unsatisfactory, I appreciate!

**Comment by andysouth** [comment]
Hi Colin,
Aha, I appreciate the trickiness.
I'm itching to have a quick tinker with the app and it's difficult for me to do that because I'd need to recreate the data.
I wonder could you try saving the shapefile with something like this and then see if github allows you to upload that ?
save(map.data, file='data/LA_map_data.rda')
cheers,
Andy

**Comment by VictimOfMaths** [comment]
Well that seemed to work. What sorcery is this? What's an .rda file?

It did occur to me that it would be sensible to restructure the code that generates the shapefiles so that the calculation of the potential mortality risk comes at the end. Then you could more easily do something like Rob suggested here https://twitter.com/R06ertSm1th/status/1248518336738209792?s=20

Would be nice to have an option to plot the age-sex rates on a univariate map, but I can't see how to easily incorporate an option to do that here without setting up a different app to do that.

**Comment by andysouth** [comment]
Haha, that's good news ! 
rda files are great. Without looking it up it's just a file version of the R object, so you can bring the object directly into R with : 
`load('data/LA_map_data.rda')`
Beware potential confusion that has tripped me up before that the object in R will have the same name as when you saved it, irrespective of any changes you make to the filename.

**Comment by andysouth** [comment]
I have to go bounce on a trampoline in the garden now but will try tinkering again over the weekend.

**Comment by VictimOfMaths** [comment]
Great stuff. Enjoy the bouncing!
